{
 "title": "Bulkhead",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Utilization Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "bulkhead_utilization ", "legendFormat": "{{ id }} - {{ instance }}" }
   ]
  },
  {
   "title": "Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bulkhead_available_calls", "legendFormat": "{{ id }} - {{ instance }}" },
    { "expr": "bulkhead_max_calls", "legendFormat": "{{ id }} - {{ instance }}" }
   ]
  },
  {
   "title": "HTTP Respons Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_response_count[1m])",
     "legendFormat": "{{ status_code }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Response Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_response_bucket[1m])) by (status_code, le))",
     "legendFormat": "p99 - {{ status_code }}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_response_bucket[1m])) by (status_code, le))",
     "legendFormat": "p50 - {{ status_code }} "
    },
    {
     "expr": "histogram_quantile(1, sum(rate(http_response_bucket[1m])) by (status_code, le))",
     "legendFormat": "p100 - {{ status_code }}"
    }
   ]
  }
 ]
}