{
 "title": "Retry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Retry Attempt Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(retry_attempt[5m])",
     "legendFormat": "#{{ number }} - {{ strategy }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "Retry Decision Rate - Should Retry?",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(retry_shouldretry[5m])",
     "legendFormat": "{{ doretry }} - {{ strategy }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Response Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_response_count[1m])",
     "legendFormat": "{{ status_code }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_response_count{status_code=~\"2..\"}[5m])) / sum(rate(http_response_count[5m]))",
     "legendFormat": "availability"
    }
   ]
  },
  {
   "title": "HTTP Response Latencies",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(http_response_bucket[1m])) by (le))",
     "legendFormat": "p100 - {{ status_code }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_response_bucket[1m])) by (le))",
     "legendFormat": "p99 - {{ status_code }}"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_response_bucket[1m])) by (le))",
     "legendFormat": "p50 - {{ status_code }} "
    }
   ]
  }
 ]
}